routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin','ProjectController@index');
Route::get('/admin/client','ClientController@index');

Route::get('/admin/project/create','ProjectController@create');
Route::get('/admin/client/create','ClientController@create');

Route::resource('project','ProjectController');
Route::resource('client','ClientController');

Route::get('/project/{project_id}/edit','ProjectController@edit')->name('edit');
Route::get('/client/{client_id}/edit','ClientController@edit')->name('editClient');

Route::get('/project/{project_id}/delete','ProjectController@delete')->name('delete');
Route::get('/client/{client_id}/delete','ClientController@delete')->name('deleteClient');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    public $primaryKey = 'project_id';
    public $fillable = ['date','image_id','website_name','description','url'];
    public $timestamps = TRUE;
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AddNewProject;
use App\Project;
use App\WebsiteImage;
use http\Env\Request;
use Illuminate\Http\Requests;
use Illuminate\Support\Facades\DB;


class ProjectController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $projects = Project::orderBy('created_at', 'DESC')
            ->paginate();
        return view('projects.index',['projects'=>$projects]);
    }

    public function create()
    {
        return view('projects.create');
    }

    public function store(\Illuminate\Http\Request $request)
    {
        $project = new Project();
        $project->website_name = $request->website_name;
        $project->description = $request->description;
        $project->date = $request->date;
        $project->url = $request->url;
        $message = [
            'website_name.required' => 'Please Enter Website Name',
            'description.required' => 'Please Enter Description',
            'url.required' => 'Please Enter URL',
            'date.required' =>'Please Select a Date',
            'website_image.required' => 'Please Select a Website Image',
        ];
        $this->validate($request,[

            'website_name' =>'required|max:100',
            'description' =>'required|max:100',
            'url' =>'required|max:100',
            'date' =>'required',
            'website_image' => 'required|image|mimes:jpeg,png,jpg|max:2048',

        ],$message);
        $image = $request->file('website_image');
        $newName = rand() . '.' . $image->getClientOriginalExtension();
        $project->website_image = $newName;
        $project->save();
        $image->move(public_path('images'),$newName);
        return redirect('/admin')->with('status','Project '. $project->project_id .' Created!')->with('path',$newName);

    }


    public function edit($project_id){

        $project = Project::find($project_id);
        return view('projects.edit',compact('project'));
    }

    public function update(\Illuminate\Http\Request $request,$project_id){
        $project = Project::find($project_id);
        $project->website_name = $request->website_name;
        $project->description = $request->description;
        $project->date = $request->date;
        $project->url = $request->url;
        $message = [
            'website_name.required' => 'Please Enter Website Name',
            'description.required' => 'Please Enter Description',
            'url.required' => 'Please Enter URL',
            'date.required' =>'Please Select a Date',


        ];
        $this->validate($request,[

            'website_name' =>'required|max:100',
            'description' =>'required|max:100',
            'url' =>'required|max:100',
            'date' =>'required',


        ],$message);

        $image = $request->file('update_website_image');
        if($image){
            $newName = rand() . '.' . $image->getClientOriginalExtension();
            $project->website_image = $newName;
            $image->move(public_path('images/website_images'),$newName);
            $project->update();
            return redirect('/admin')->with('status','Project '. $project->project_id .' Updated!');
        }
        else{
            $project->website_image;
            $project->update();
            return redirect('/admin')->with('status','Project '. $project->project_id .' Updated!');
        }

    }

    public function delete($project_id){

      Project::find($project_id)->delete();
      return redirect('/admin')->with('status','Project '. $project_id .' Deleted!');
    }
}

resources/views/projects/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Lanka Designer | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>A</b>LT</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Lanka</b> Designer</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
    @include('layouts.sidebar')
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->


        <!-- Main content -->
        <div class="pagenav">
            <div class="box">
                <div class="page-header no-border" style="padding-right:40px;">
                    <a href="/admin/project/create"><span class="label label-primary pull-right"><i class="fa fa-plus-circle">
            </i>

              Add New Project

            </span></a>
                    <h3>&nbsp;&nbsp;&nbsp;<span class="fa fa-arrow-circle-o-left"></span> Home - Projects</h3>
                </div>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">Create</a></li>
                </ol>
            </div>
        </div>

        <div class="box-body">
                @include('layouts.alert')
                <div class="box">
                <form role="form" enctype="multipart/form-data" method="POST" novalidate="novalidate" action="{{route('project.store')}}">
                    {{ csrf_field() }}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="website_name">Website Name</label>
                            <input type="text" class="form-control" name="website_name" id="website_name" value="{{(old('website_name'))}}">
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea rows="6" type="text" class="form-control" name="description" id="description" value="{{(old('description'))}}"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="url">URL</label>
                            <input type="url" class="form-control" name="url" id="url" value="{{(old('url'))}}">
                        </div>
                        <div class="form-group">
                            <label for="date">Date</label>
                            <input type="date" class="form-control" name="date" id="date" value="{{(old('date'))}}">
                        </div>
                        <div class="form-group">
                            <label for="website_image">Image</label>
                            <input type="file" class="form-control" name="website_image" id="website_image">
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-success">Publish</button>
                        <button type="reset" class="btn btn-bitbucket">Reset</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
    @include('layouts.footer')
</div>
</divcl>

<!-- ./wrapper -->
<!--Content-->

<!-- jQuery 3 -->
<script src="/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.min.js"></script>
<!-- Sparkline -->
<script src="/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap  -->
<script src="/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- SlimScroll -->
<script src="/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- ChartJS -->
<script src="/bower_components/chart.js/Chart.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/dist/js/pages/dashboard2.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>


</body>
</html>

resources/views/projects/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Lanka Designer | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>A</b>LT</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Lanka</b> Designer</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
    @include('layouts.sidebar')
    <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->


        <!-- Main content -->
        <div class="pagenav">
            <div class="box">
                <div class="page-header no-border" style="padding-right:40px;">
                    <a href="/admin/project/create"><span class="label label-primary pull-right"><i class="fa fa-plus-circle">
            </i>

              Add New Project

            </span></a>
                    <h3>&nbsp;&nbsp;&nbsp;<span class="fa fa-arrow-circle-o-left"></span> Home - Projects</h3>
                </div>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">Create</a></li>
                </ol>
            </div>
        </div>

        <div class="box-body">
            @include('layouts.alert')
            <div class="box">
                <form role="form" method="POST" enctype="multipart/form-data" action="{{route('project.update',$project->project_id)}}">
                    {{csrf_field()}}
                    {{ method_field('PUT') }}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="website_name">Website Name</label>
                            <input type="text" class="form-control" name="website_name" id="website_name" value="{{$project->website_name}}">
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea rows="6" type="text" class="form-control" name="description" id="description" value="{{$project->description}}"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="url">URL</label>
                            <input type="url" class="form-control" name="url" id="url" value="{{$project->url}}">
                        </div>
                        <div class="form-group">
                            <label for="date">Date</label>
                            <input type="date" class="form-control" name="date" id="date" value="{{$project->date}}">
                        </div>
                        <div class="form-group">
                            <label for="website_image">Image</label>
                            <input type="file" class="form-control" name="update_website_image" id="update_website_image">
                        </div>
                        <div class="col-sm-4">
                        <img class="img-responsive" src="/images/website_images/{{$project->website_image}}">
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-success">Update</button>
                        <button type="reset" class="btn btn-bitbucket">Reset</button>
                        <a href="/admin" class="btn btn-warning" role="button" aria-disabled="true">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg">

        </div>


    </div>
    </divcl>
</div>
<!-- ./wrapper -->
<!--Content-->

<!-- jQuery 3 -->
<script src="/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.min.js"></script>
<!-- Sparkline -->
<script src="/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap  -->
<script src="/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- SlimScroll -->
<script src="/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- ChartJS -->
<script src="/bower_components/chart.js/Chart.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/dist/js/pages/dashboard2.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>


</body>
</html>

resources/views/projects/index.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Lanka Designer | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="bower_components/Ionicons/css/ionicons.min.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="bower_components/jvectormap/jquery-jvectormap.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="dist/css/skins/_all-skins.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">

    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Lanka</b> Designer</span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
  @include('layouts.sidebar')
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->


    <!-- Main content -->
    <div class="pagenav">
      <div class="box">
        <div class="page-header no-border" style="padding-right:40px;">
          <a href="admin/project/create"><span class="label label-primary pull-right"><i class="fa fa-plus-circle">
            </i>

              Add New Project

            </span></a>
          <h3>&nbsp;&nbsp;&nbsp;<span class="fa fa-arrow-circle-o-left"></span> Home - Projects</h3>
        </div>
        <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
          <li><a href="#">Projects</a></li>
        </ol>
        </div>
      </div>



    <div class="box-body">
        @include('layouts.alert')
    <div class="box">
      <table class="table">
          <thead>
          <tr>
              <th>Project ID</th>
              <th>Name</th>
              <th>Date</th>
              <th>Action</th>

          </tr>
          </thead>
          <tbody>
          @foreach($projects as $project)
          <tr>
            <td class="media">
              <div class="media-left">
                <span class="glyphicon glyphicon-folder-open -lg">
                  <b><a href="#">
                      {{ \App\Facades\GlobalServiceFacade::getPaddedId($project['project_id'])}}</a>
                  </b>
                </span>
              </div>
            </td>
            <td>
              {{$project['website_name']}}
            </td>
            <td>
              {{$project['date']}}
            </td>
            <td>
              <div class="btn-group">
                <button type="button" class="btn btn-orange dropdown-toggle legitRipple" data-toggle="dropdown">
                  <i class=" fa fa-navicon position-left"></i>

                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li>
                    <a href="{{route('edit',$project->project_id)}}"><i class="fa fa-pencil-square-o"></i> Edit</a>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="{{route('delete',$project->project_id)}}"><i class="fa fa-remove"></i> Delete</a>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
    @include('layouts.footer')
</div>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->

</divcl>
<!-- ./wrapper -->
<!--Content-->

<!-- jQuery 3 -->
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/adminlte.min.js"></script>
<!-- Sparkline -->
<script src="bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap  -->
<script src="plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- SlimScroll -->
<script src="bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- ChartJS -->
<script src="bower_components/chart.js/Chart.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="dist/js/pages/dashboard2.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="dist/js/demo.js"></script>




</body>

</html>