routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin','ProjectController@index');
Route::get('/admin/client','ClientController@index');

Route::get('/admin/project/create','ProjectController@create');
Route::get('/admin/client/create','ClientController@create');

Route::resource('project','ProjectController');
Route::resource('client','ClientController');

Route::get('/project/{project_id}/edit','ProjectController@edit')->name('edit');
Route::get('/client/{client_id}/edit','ClientController@edit')->name('editClient');

Route::get('/project/{project_id}/delete','ProjectController@delete')->name('delete');
Route::get('/client/{client_id}/delete','ClientController@delete')->name('deleteClient');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    public $primaryKey = 'client_id';
    public $fillable = ['client_name','client_image'];
    public $timestamps = TRUE;
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $clients = Client::orderBy('created_at', 'DESC')
            ->paginate();
        return view('clients.index',['clients'=>$clients]);
    }

    public function create()
    {
        return view('clients.create');
    }

    public function store(\Illuminate\Http\Request $request)
    {
        $client = new Client();
        $client->client_name = $request->client_name;
        $client->client_image = $request->client_image;
        $message = [
            'client_name.required' => 'Please Enter Client Name',
            'client_image.required' => 'Please Choose a Client Logo',
        ];
        $this->validate($request,[

            'client_name' =>'required|max:100',
            'client_image' =>'required',

        ],$message);
        $image = $request->file('client_image');
        $newName = rand() . '.' . $image->getClientOriginalExtension();
        $client->client_image = $newName;
        $client->save();
        $image->move(public_path('images'),$newName);
        return redirect('/admin/client/')->with('status','Project '. $client->client_id .' Created!')->with('path',$newName);

    }


    public function edit($client_id){

        $client = Client::find($client_id);
        return view('clients.edit',compact('client'));
    }

    public function update(\Illuminate\Http\Request $request,$client_id){
        $client = Client::find($client_id);
        $client->client_name = $request->client_name;
        $message = [
            'client_name.required' => 'Please Enter Client Name',

        ];
        $this->validate($request,[
            'client_name' =>'required|max:100',

        ],$message);

        $image = $request->file('client_image');
        if($image){
            $newName = rand() . '.' . $image->getClientOriginalExtension();
            $client->client_image = $newName;
            $image->move(public_path('images/logo'),$newName);
            $client->update();
            return redirect('/admin/client')->with('status','Client '. $client->client_id .' Updated!');
        }
        else{
            $client->client_image;
            $client->update();
            return redirect('/admin/client')->with('status','Client '. $client->client_id .' Updated!');
        }

    }

    public function delete($client_id){

        Client::find($client_id)->delete();
        return redirect('/admin/client/')->with('status','Project '. $client_id .' Deleted!');
    }
}

resources/views/clients/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Lanka Designer | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>A</b>LT</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Lanka</b> Designer</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
    @include('layouts.sidebar')
    <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->


        <!-- Main content -->
        <div class="pagenav">
            <div class="box">
                <div class="page-header no-border" style="padding-right:40px;">
                    <a href="/admin/project/create"><span class="label label-primary pull-right"><i class="fa fa-plus-circle">
            </i>

              Add New Client

            </span></a>
                    <h3>&nbsp;&nbsp;&nbsp;<span class="fa fa-arrow-circle-o-left"></span> Home - Clients</h3>
                </div>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#">Clients</a></li>
                    <li><a href="#">Create</a></li>
                </ol>
            </div>
        </div>

        <div class="box-body">
            @include('layouts.alert')
            <div class="box">
                <form role="form" enctype="multipart/form-data" method="POST" novalidate="novalidate" action="{{route('client.store')}}">
                    {{ csrf_field() }}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="website_name">Client Name</label>
                            <input type="text" class="form-control" name="client_name" id="client_name" value="{{(old('client_name'))}}">
                        </div>
                        <div class="form-group">
                            <label for="website_image">Logo</label>
                            <input type="file" class="form-control" name="client_image" id="client_image">
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-success">Publish</button>
                        <button type="reset" class="btn btn-bitbucket">Reset</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
    @include('layouts.footer')
</div>
</divcl>

<!-- ./wrapper -->
<!--Content-->

<!-- jQuery 3 -->
<script src="/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.min.js"></script>
<!-- Sparkline -->
<script src="/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap  -->
<script src="/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- SlimScroll -->
<script src="/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- ChartJS -->
<script src="/bower_components/chart.js/Chart.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/dist/js/pages/dashboard2.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>


</body>
</html>

resources/views/clients/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Lanka Designer | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>A</b>LT</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Lanka</b> Designer</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
    @include('layouts.sidebar')
    <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->


        <!-- Main content -->
        <div class="pagenav">
            <div class="box">
                <div class="page-header no-border" style="padding-right:40px;">
                    <a href="/admin/project/create"><span class="label label-primary pull-right"><i class="fa fa-plus-circle">
            </i>

              Add New Client

            </span></a>
                    <h3>&nbsp;&nbsp;&nbsp;<span class="fa fa-arrow-circle-o-left"></span> Home - Clients</h3>
                </div>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#">Clients</a></li>
                    <li><a href="#">Create</a></li>
                </ol>
            </div>
        </div>

        <div class="box-body">
            @include('layouts.alert')
            <div class="box">
                <form role="form" enctype="multipart/form-data" method="POST" novalidate="novalidate" action="{{route('client.update',$client->client_id)}}">
                    {{ csrf_field() }}
                    {{method_field('PUT')}}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="website_name">Client Name</label>
                            <input type="text" class="form-control" name="client_name" id="client_name" value="{{$client->client_name}}">
                        </div>
                        <div class="form-group">
                            <label for="website_image">Logo</label>
                            <input type="file" class="form-control" name="client_image" id="client_image">
                        </div>
                    <div class="col-sm-4">
                        <img class="img-responsive" src="/images/logo/{{$client->client_image}}">
                    </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-success">Update</button>
                        <button type="reset" class="btn btn-bitbucket">Reset</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
    @include('layouts.footer')
</div>
</divcl>

<!-- ./wrapper -->
<!--Content-->

<!-- jQuery 3 -->
<script src="/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.min.js"></script>
<!-- Sparkline -->
<script src="/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap  -->
<script src="/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- SlimScroll -->
<script src="/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- ChartJS -->
<script src="/bower_components/chart.js/Chart.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/dist/js/pages/dashboard2.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>


</body>
</html>

resources/views/clients/index.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Lanka Designer | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>A</b>LT</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Lanka</b> Designer</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
    @include('layouts.sidebar')
    <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->


        <!-- Main content -->
        <div class="pagenav">
            <div class="box">
                <div class="page-header no-border" style="padding-right:40px;">
                    <a href="/admin/client/create"><span class="label label-primary pull-right"><i class="fa fa-plus-circle">
            </i>

              Add New Client

            </span></a>
                    <h3>&nbsp;&nbsp;&nbsp;<span class="fa fa-arrow-circle-o-left"></span> Home - Clients</h3>
                </div>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#">Clients</a></li>
                </ol>
            </div>
        </div>



        <div class="box-body">
            @include('layouts.alert')
            <div class="box">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Client ID</th>
                        <th>Name</th>
                        <th>Action</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($clients as $client)
                        <tr>
                            <td class="media">
                                <div class="media-left">
                <span class="glyphicon glyphicon-folder-open -lg">
                  <b><a href="#">
                      {{ \App\Facades\GlobalServiceFacade::getPaddedId($client['client_id'])}}</a>
                  </b>
                </span>
                                </div>
                            </td>
                            <td>
                                {{$client['client_name']}}
                            </td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-orange dropdown-toggle legitRipple" data-toggle="dropdown">
                                        <i class=" fa fa-navicon position-left"></i>

                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li>
                                            <a href="{{route('editClient',$client->client_id)}}"><i class="fa fa-pencil-square-o"></i> Edit</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="{{route('deleteClient',$client->client_id)}}"><i class="fa fa-remove"></i> Delete</a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @include('layouts.footer')
</div>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->

</divcl>
<!-- ./wrapper -->
<!--Content-->

<!-- jQuery 3 -->
<script src="/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.min.js"></script>
<!-- Sparkline -->
<script src="/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap  -->
<script src="/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- SlimScroll -->
<script src="/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- ChartJS -->
<script src="/bower_components/chart.js/Chart.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/dist/js/pages/dashboard2.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>




</body>

</html>